### ISSUE TITLE
Great Job ! minor issue : graph not visible on browser

### ISSUE THREAD

**Issue by djdav** [sharandac/powermeter#6]
Hello, first, congratulations this looks impressive and well designed. 

I've uploaded successfully, setting the revision of "WebSockets@=2.3.4" (otherwise error message during compilation).

I can connect successfully but checking the webpage I cannot get the graph and the layout of the page seems incorrect on Chrome on my phone, Chrome and Explorer on PC. Which browser did you recommend ? 

thanks,

**Comment by sharandac** [comment]
Thanks for your feedback. Oh no, but that sounds interesting. Maybe not all the files in the data directory have been transferred correctly. Especially the jquery-lastest.min.js.

I myself use Firefox under Linux for this. But I don't have any problems with it on Android either.
